---
title: "Plotly"
author: "Boxuan Li"
date: "11/14/2017"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r loading packages, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 5,
  fig.asp = .6,
  out.width = "80%"
)

library(tidyverse)
library(rnoaa)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r read and tidy dateset, message=FALSE, warning=FALSE}
Ins <- read_csv("../data/instacart_train_data.csv.zip") %>%
  clean_names()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Barplot of Number of Purchase for 10 Most Popular Aisles

```{r barplot, message=FALSE, warning=FALSE}
Ins %>%
  group_by(., aisle) %>%
  summarize(., count = n()) %>%
  top_n(., 10) %>%
  mutate(., aisle = as.factor(aisle),
            aisle = fct_reorder(aisle, count)) %>%
  plot_ly(x = ~aisle, y = ~count, color = ~aisle, type = "bar", colors = "Set1") %>%
  layout(title = 'The 10 Most Popular Aisles with Most Orders')
```

Column {data-width=450, .tabset}
-----------------------------------------------------------------------

### Boxplot for the Distribution of Order Hour by Day in a Week

```{r boxplot, message=FALSE, warning=FALSE}
days_week <- c("Sunday", "Monday", "Tuesday", "Wednesday", "Thusday", "Friday", "Saturday") %>%
  factor(., levels = c("Monday", "Tuesday", "Wednesday", "Thusday", "Friday", "Saturday", "Sunday"))

Ins.boxplot <- Ins %>%
  select(., order_id, day_in_week = order_dow, order_hour_of_day) %>%
  mutate(., day_in_week = days_week[day_in_week+1]) %>%
  distinct(., order_id, day_in_week, order_hour_of_day) %>%
  ggplot(., aes(x = day_in_week, order_hour_of_day, color = day_in_week)) +
  geom_boxplot(position = "dodge") +
  labs(title = "Distribution of Order Hour by Day in a Week",
       x = "Day",
       y = "Order Hour") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "none")

ggplotly(Ins.boxplot)
```

### Piechart of Orders from Each Department

```{r, piechart, message=FALSE, warning=FALSE}
Ins %>%
  group_by(., department) %>%
  summarize(., count = n()) %>%
  plot_ly(., labels = ~department, values = ~count, type = 'pie', colors = "Set1") %>%
  layout(title = 'Total Number of Orders by Department')
```